server:
  port: 8082

spring:
  application:
    name: volcamp-2025-example3

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:12b
        # model: mistral-small-7b

logging:
  level:
    root: INFO
  pattern:
    console: "%-5level %msg%n"