server:
  port: 8080

spring:
  application:
    name: volcamp-2025-example1

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:12b
        # model: gemma3:12b
        # model: mistral-small-7b

logging:
  level:
    root: INFO
  pattern:
    console: "%-5level %msg%n"